name: Build bot

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          docker build -t criteord/memcached_proxy .
          mkdir bin/
          docker run --rm -v $(pwd)/bin:/data -- criteord/memcached_proxy /bin/sh -c "cp /mem* /data"

        
      - uses: actions/upload-artifact@v1
        with:
          name: bin
          path: bin/
        
