name: Build bot

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          docker build -t criteord/memcached_proxy .
          docker run --rm -v $(pwd):/data criteord/memcached_proxy /bin/cp memcached_cluster_proxy /data
        
      - uses: actions/upload-artifact@v1
        with:
          name: memcached_cluster_proxy
          path: memcached_cluster_proxy
        
