name: Build bot

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          docker build -t memcached_proxy .
        
      - uses: actions/upload-artifact@v1
        with:
          name: memcached_cluster_proxy
          path: memcached_cluster_proxy
        
