on:
  push:
    tags:
      - 'v*'
      
name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Build
        run: |
          docker build -t criteord/memcached_proxy .
          mkdir bin/
          docker run --rm -v $(pwd)/bin:/data -- criteord/memcached_proxy /bin/sh -c "cp /mem* /data"
      
      - name: Upload
        uses: fnkr/github-action-ghr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_PATH: bin/
          GHR_COMPRESS: gz
